AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Amazon Cognito Identity Pool, Roles, and Role Attachment.
Parameters:
  CognitoIdentityPoolName:
    Type: String
  CognitoUserPoolClientID:
    Type: String
  CognitoUserPoolProviderName:
    Type: String

Resources:
  CognitoIdentityPool:
    Type: 'AWS::Cognito::IdentityPool'
    Properties:
      IdentityPoolName: !Ref CognitoIdentityPoolName
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        -  ClientId: !Ref CognitoUserPoolClientID
           ProviderName: !Ref CognitoUserPoolProviderName
           ServerSideTokenCheck: true

  CognitoIdentityPoolAuthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join [ '', [ !Ref 'AWS::StackName', 'Auth' ] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "cognito-idp.amazonaws.com"
            Action:
            - 'sts:AssumeRole'

  CognitoIdentityPoolUnauthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join [ '', [ !Ref 'AWS::StackName', 'Unauth' ] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "cognito-idp.amazonaws.com"
            Action:
            - 'sts:AssumeRole'

  RoleAttachment:
    Type: 'AWS::Cognito::IdentityPoolRoleAttachment'
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoIdentityPoolAuthRole.Arn
        unauthenticated: !GetAtt CognitoIdentityPoolUnauthRole.Arn
      RoleMappings:
        IDENTITYPROVIDER:
          AmbiguousRoleResolution: Deny
          Type: Token

Outputs:
  CognitoIdentityPoolID:
    Description: The ID for the Cognito Identity Pool
    Value: !Ref CognitoIdentityPool
    Export:
      Name: !Join [ '-', [ !Ref CognitoIdentityPoolName, 'IdentityPoolID' ] ]